### ISSUE TITLE
Steam deck - core dump

### ISSUE THREAD

**Issue by deasmi** [SteamGridDB/SGDBoop#25] opened 2022-09-02 18:42 UTC
I have been trying to track down why this wasn't working on steam deck, Chrome or Firefox.

It does work correctly if triggered from the command line, I am using the command line from the .desktop file
` /usr/bin/flatpak run --branch=stable --arch=x86_64 --command=SGDBoop --file-forwarding com.steamgriddb.SGDBoop @@u sgdb://boop/logo/2283/nonsteam @@
`
However when triggered from Chrome it gives a core dump as attached file.
Captured from the logs program flatpak 

[log_messages.txt](https://github.com/SteamGridDB/SGDBoop/files/9480360/log_messages.txt)

Chrome is triggering the executable as if I monitor with constant ps -ef I can see SGDBoop running.

**Comment by rstrube** [comment] 2022-09-02 21:05
I believe I'm running into the same issue.  SGDBoop appears to be crashing for me as well when running from the browser.

**Comment by Daegalus** [comment] 2022-09-05 02:26
Having the same issue. You can run it fine if you do `xdg-open sgdb://<URL>` but the browsers can't launch it.

I haven't dug into it myself but skimming through the coredump posted, it's blowing up on Bluetooth?

I might try adding strace to the desktop file to see what it says.

**Comment by doZennn** [comment] 2022-09-05 02:53
We can't seem to reproduce this or single out the issue from the posted log, so any more info is welcome!

**Comment by deasmi** [comment] 2022-09-05 17:16
@doZennn when I have some time I will do some more testing and see if I can get an actual core dump.

**Comment by deasmi** [comment] 2022-09-07 18:49
I am going to have to apologise for not following every troubleshooting step. 

Clean install of steam deck and this still happened. 

xdg-open sgdb://book/test 

On the command line works. 

Chrome and Firefox nothing. 

Then I noticed the opt out of beta notice in troubleshooting steps which I'd missed.

On stable this doesn't happen. 

I still think worth tracking down as when beta->stable perhaps will break everyone.

**Comment by doZennn** [comment] 2022-09-08 01:48
If you don't mind going into beta again, can you try setting the default browser with
```
xdg-settings set default-web-browser [name of the .desktop for a browser]
```
The browser .desktop names for the Flatpaks should be `com.google.Chrome.desktop` / `org.mozilla.firefox` but i'm not sure.  


And also this (if the above doesn't work)
```
xdg-settings set default-url-scheme-handler sgdb com.steamgriddb.SGDBoop.desktop
```
Someone else was having a similar issue and fixed it this way, I'm not sure if this is the same issue or if they had a bad configuration.

**Comment by Daegalus** [comment] 2022-09-08 01:52
As a side note, I downgraded to stable also, but it still doesn't work. I'll try the steps you mentioned to see if anything is amiss.

**Comment by deasmi** [comment] 2022-09-08 19:25
@doZennn resetting default-web-browser and default-url-scheme-handler didn't help.

However looking at the attached, I'm not convinced this gets as far as calling sgdboop, looks like xdg-desktop-portal-kde is crashing which would make this a steam deck bug.

**Comment by doZennn** [comment] 2022-09-08 19:35
Interesting, let's keep this open until the beta goes to stable, no harm in figuring it out anyway.

**Comment by mpaterakis** [comment] 2022-09-08 20:24
> I am already sure that the scheme handler is set to sgdb, since I've been. Looking at that. But I haven't checked the default browser setting.
Don't ignore the step of re-setting of the handler. It doesn't get fixed unless you do that. YES, even setting it to the same option again.

> I'm not convinced this gets as far as calling sgdboop, looks like xdg-desktop-portal-kde is crashing 
That's what I'm getting here as well.

**Comment by failzers** [comment] 2022-09-09 16:52
https://github.com/ValveSoftware/SteamOS/issues/775 

could be related to this. the portal service is currently broken on Beta.

**Comment by Daegalus** [comment] 2022-09-10 00:50
> > I am already sure that the scheme handler is set to sgdb, since I've been. Looking at that. But I haven't checked the default browser setting.
> 
> Don't ignore the step of re-setting of the handler. It doesn't get fixed unless you do that. YES, even setting it to the same option again.
> 
> > I'm not convinced this gets as far as calling sgdboop, looks like xdg-desktop-portal-kde is crashing 
> 
> That's what I'm getting here as well.

Ya reset everything and still nada for me. I'm on stable, all my xdg settings are good.

Looks like it's a KDE portal issue. Maybe it's time I followed that guide to install Gnome instead, it has abetter touch screen experience anyway

**Comment by callit** [comment] 2022-09-25 03:10
Something odd happened. I was messing around with Flatseal. I gave Firefox access to all files and relaunched Firefox. Around the same time, I relaunched firefox in a different way. I have two firefox icons sometimes. While Firefox was running, I clicked the left icon which appeared to be inactive. i believe a new Firefox profile may have been created because the new Firefox window had a light theme instead of the dark theme that I had set it to.

In the new light theme browser, the boop worked.

I dropped Firefox's access down to just my home folder, and the test button stopped working.

Using both the flatpack version of firefox and sgdboop on Steam Deck

**Comment by jonasborn** [comment] 2022-09-25 10:48
@callit I've also thought about an issue with the access rights. Using a portable version of Firefox
(https://wiki.ubuntuusers.de/Portable_Firefox/ - German), I was able to use sgdboop without problems.
It seems, the flatpak version of Firefox and Chrome are not able to call whatever they want (in my case neither xdg-open nor sgdboop directly). This issue is known for snaps under Ubuntu - I'll have to do a few more tests here to confirm for sure. This problem was also mentioned here: https://steamcommunity.com/app/1675200/discussions/1/3448087385661840722/ - unfortunately without any technical details.

**Comment by doZennn** [comment] 2022-09-25 10:50
Have you tried restarting xdg-desktop-portal after entering desktop mode?
`systemctl --user status xdg-desktop-portal`

**Comment by jonasborn** [comment] 2022-09-25 11:06
@doZennn Thank you, saw the new entry on the page just now. Can confirm this working in Chrome and Firefox in Desktop Mode. Not working in Gaming Mode using Chrome.

**Comment by nille02** [comment] 2022-10-23 18:12
Jep, loops like its a problem with the xdg-desktop-portal. I got this in the journal each time. 

```
Oct 23 20:07:19 steamdeck systemd[1064]: Started app-flatpak-com.steamgriddb.SGDBoop-8519.scope.
Oct 23 20:07:20 steamdeck xdg-desktop-portal[8473]: Invalid MIT-MAGIC-COOKIE-1 key
Oct 23 20:07:20 steamdeck kernel: SGDBoop[8529]: segfault at 10 ip 00007f99c8ce72fd sp 00007ffcb6206e30 error 4 in libiup.so[7f99c8cda000+b8000]
Oct 23 20:07:20 steamdeck kernel: Code: ff ff 66 66 2e 0f 1f 84 00 00 00 00 00 f3 0f 1e fa 55 53 48 89 fb 48 83 ec 18 48 85 d2 74 5e 80 3a 5f 75 06 80 7a 01 40 74 1b <48> 8b 7b 10 48                                                                       83 c4 18 b9 01 00 00 00 5b 5d e9 ef ab ff ff 0f 1f
Oct 23 20:07:20 steamdeck systemd[1]: Started Process Core Dump (PID 8532/UID 0).
Oct 23 20:07:21 steamdeck xdg-desktop-portal-kde[7037]: xdp-kde-background: GetAppState called: no parameters
Oct 23 20:07:21 steamdeck xdg-desktop-portal-kde[7037]: xdp-kde-background: NotifyBackground called with parameters:
Oct 23 20:07:21 steamdeck xdg-desktop-portal-kde[7037]: xdp-kde-background:     handle:  "/org/freedesktop/portal/desktop/notify/background4"
Oct 23 20:07:21 steamdeck xdg-desktop-portal-kde[7037]: xdp-kde-background:     app_id:  "com.nextcloud.desktopclient.nextcloud"
Oct 23 20:07:21 steamdeck xdg-desktop-portal-kde[7037]: xdp-kde-background:     name:  "Nextcloud Desktop"
Oct 23 20:07:22 steamdeck systemd-coredump[8533]: [🡕] Process 8529 (SGDBoop) of user 1000 dumped core.
```
Full Log:
https://pastebin.com/U8fWFgpy

**Comment by doZennn** [comment] 2023-09-03 15:56
SteamOS fix should be in live by now, closing.

**Closed by doZennn** 2023-09-03 15:56 UTC
Labels: bug
